services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "../certificates/:/var/www/certificates/:ro"
            - "./.docker/nginx/local.conf:/etc/nginx/conf.d/local.conf"
            - "./.docker/nginx/logs/:/var/log/nginx/"
            - "./:/var/www/hymns.vq.local/"
        links:
            - php-fpm

    php-fpm:
        build: ./.docker/php-fpm
        volumes:
            - "./.docker/php-fpm/local.ini:/usr/local/etc/php/conf.d/40-local.ini"
            - "./.docker/php-fpm/fpm.conf:/usr/local/etc/php-fpm.d/www.conf"
            - "./.docker/php-fpm/logs/:/var/log/"
            - "./:/var/www/hymns.vq.local/"
        links:
            - mysql
            - redis

    mysql:
        image: mysql:8
        hostname: hymns.vq.local
        ports:
            - "3306:3306"
        volumes:
            - "./.docker/mysql/logs/:/var/log/mysql/"
#            - "./.docker/mysql/data/:/var/lib/mysql/"
            - "./.docker/mysql/setup.sql:/docker-entrypoint-initdb.d/1.sql"
#        command: --mysql-native-password=ON
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: false
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: hymns_Root_Pass
            MYSQL_DATABASE: hymns_db
            MYSQL_USER: hymns_user
            MYSQL_PASSWORD: hymns_Pass

    redis:
        image: redis:7-alpine
        hostname: hymns.vq.local
        ports:
            - "6379:6379"
        volumes:
            - "./.docker/redis/logs/:/var/log/"
            - "./.docker/redis/data/:/data/"
